apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: matrix-secret
  namespace: matrix
spec:
  encryptedData:
    secrets.yaml: AgAPvyl0Y1wTKEXuozWj/h3+34QFrXa37QxLdk6hP0oUinfyqg+So5ozIISYKwa4veehLYfxlRI3PjoP7nlog3qExStqS1bLc435aKlVYihdiwyQMg/XACmWpBGZTL319ZbLCmEI5igWE6U6UsZVzUT6CbURf0slQMYqUQh0u+hG6x9Ukp8VGrE1gMgh9mR6eYQa17f9sI7SZcfH80xqT8A8WvYzsC2hE+iVMbOiXGUsxKeScECVKUwR0weiYxeDBqTc+gGNkyEIioaNOYPIka2g73oNj3d15/Y4XxHjFnCYgRs+UY7YDHXEk0E6oVuEwB7TzK3C4U2LQ8aJisRUwfGxeY3xTgPgoKD2DeM5f4dGs8hsuyisflmaAnkWWuLwsCWplzUMK4aISu4nzYeX9Wj0Zy/kAEOosul4+F73/uMmytBjTK0GrkNRvwM6ctoIkpBJYj+OsEUdXd7Ok8/pWmZ7wSz8Dad0aD1itUDqcm8OWvKHN+2aWkoJXLXNB7bHeIisi/cO+jRiUd0opbl/EiYK8/YsBTrIJwGzdHo81vRRFv0q3siJOTAYPfqDnj6zqVciIW0RVYvk5z/d6PDAtz4HPPG3lG85XLLjiJohefwvpZZde9FuxGyoZam18K1nKrMmL2K1N+uZ9aCjKuOz1elKGFa2UZqq0H6jz5eQQA3G0U4noqsWWnMP5EGAHhnuU2G08GKQBZi01QrwRxjaZg5RVeZXKcqEKs3lji5/xqCiNPF5Lwjb/xbZgpb9aOCYILndAf2z4/vMZNA18oCNyEy4VIMazjtiltx981YFc3ca6E+sjBqmFF/SYXMXNetBb7s4qJ1nCZzc1H4xQROiwd7Ux/VCWkuuV0QDVBYTSh9fCru6tyfGLYmB+ASF+4PdbcAWMGnAVzGVpdS0shjHW8jCS4EcxB8l9+WLTpQNiQJYEiQaHxa0BtZbFdJns3Uct5KLJ90ESE9CTrVahEsjb2gWLYEZ6IvLSmwE/IDWspJHMRqijcGLa+7rw2HadRM+x4Ops4NHJyj6o6SC7DZ8H7HRpo+HSXZofTNsSpTG3vK/73p0p4VwoCU0nDPtRbayXVl72sUbgZjwBYx/5dLwShhLlMb8bPmb5vbcMFb6y6r4oTJ135VtIwyuiHY9y6ul9ZCWy8ptiG7oWdar80d5nZtf+Q5X59kON8BbjO2GURJGwnaZMbcJI75PKtKavVpeXT4sVCPxjMk5FFLWuuRuFis=
  template:
    metadata:
      creationTimestamp: null
      name: matrix-secret
      namespace: matrix
    type: Opaque
