apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: matrix-secret
  namespace: matrix
spec:
  encryptedData:
    macaroon_secret_key: AgBROBTQTZp4TgMsMntp//aNmo3AhNjGjgekyVUmx+9ou+JF1vXlCJ0gK0svpZ7PdbvisjafwG7hgPDroCfF+W00WYruWKwpE1K+d6AIzYrIWYWEowL1Hyyy5mt9ruEQLHSXQDo3TYGpKHGb6CEgtTeQ8leYqVmGm1a8kd0Mq36R0PXyon2wytw58B6TYgzvaZAjJHCLORfZjjgD8eFYxzLb1T63RvYyEku+zf7wi2HgOLSOPDP0K8G/t6GuaoOm88qgTyyk3+fdKj1gXCST03PBDlM2yfJg+3xnyyT7ZvVLeRO9fDwhhL44KiMwARTcYidJhsELHSEsDnEkz+HNtr28jVnqwgScrRLGHsJE3bY8h92W1cN5t2Ued9QCAU97JDwSG5XEG9kHdF60FizwV8X+21D6YxKxq3Lz0R0ZHx3ilq4UBYVlS9AFO2PReP1Tyv+7EEYwk0o37Vrv1a+oB2i+s7JVhBuUKOBvoyog1Zm1te3KucBVXHwuWn3YKviTbHF3wmzrCpFCD3jgLb7taAgoWN9U0u/0+1pb1teGFfjHN/1OcP7LKww9HoJBcTPGmc8jd1NGoL7EKtxHmqYRiDWTh7e7dZVAfok/gnfZfWws5hVf5EhNSeSsntkCFXIh3sDnSLBx49h/iERP3f2qtoDEkZnNtyWVgN6OY6Xa1pom3TgiqPT2wp6bZkQCmX7VSe9dNOw5JyPCPDL1nr3VFRK5lOVBZJqNv5r7e7efya5MmXArM0YEkjn3EYIbEbNftOn9FIB3u2pYDLWNhpo=
  template:
    metadata:
      creationTimestamp: null
      name: matrix-secret
      namespace: matrix
    type: Opaque
