apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: matrix-secret
  namespace: matrix
spec:
  encryptedData:
    secrets.yaml: AgBF01DbIM7ZG/IZrwq3FdV/3SMptEQd2LFmz4nS+5ic7wTmLi00fJcgxQqsLDpjflfEYdnMWb/UAGykc/8nKC3ki4dzRF7uNBQ/9K/cLtNB2RUrE79G6QurGC5b8PrfXvBfxbgRwHymmNid0Y+fJmdnVTyv5WZC2NfOdsMwlwZm2i4nS9COsb1GuqM9NroTKpOCTIPjRaM0dsnR1g0umUHcJ7WcHOyA6rtceCAZFIOpnsKHY5kqRgy163Kimk/WvWq2SehmyWGtWfR3JPjdKRJaIqeDBZxJKMir9gYXp+2UsgPlDeO1NN07tONjyxo1Z6T1lQpma4VMhmkItShPcM2caJWoJU40YrCCxaHRTQFBWUjAts7Dk7rMkYeTCjkmzHx1Nfmft7UkwXFqgny4wJVZ3bnNYvpztFuAQMvsh1C5X4nlwmf7PYgj4UB7sqY1YNrzZUrtSg0xK+qgY/LcTE+ZpE2XBL3+iScNvkPpe6zln4TdsagwdXEMwd62bGeNK2elB/Ynoy9LKRG98s0y6OW7szLp0ZNXEBOCCImvYtqRgrzBkpl2MXrZ8F1+YA4z+SeJM6CQLcaT11k9dPHBa2CTtz9zzEqezvXhEI3hFoGJBpC2f3XdrskfpIRmUc8Xfb6iIlv8TXa6GUSOLiVUzSIZLZ4cA2idQ00264VqSBejKvfei3+ZLHBbT1RsWm1iNWxZIo/KZdmFc3ENSGO1Ou/ZlDa0TdLYPsIJbdBuNmXTjNsMLjHDiuvBXOGi3dDS3lquq3Tyb38q3si9Fayyr+9lKE+2KM3exWPznZh+jqDVgbGrAArQsPR/u1uqHAkV4sWcwcD39OWFzntcvpYCNF220g8QW9BdqCTUH3pfFvld79/jykRRrBsSiSyfatECeY2STPzQ35KDcnONZafcD9iiNm5HEpUnIHUq3IOEqxTiwlVA+FwpvU6ZinMmjiYPCKkjhpuX4HXG5YCRC/vqilGWB/bxCB8Nw8/Uu65wWhknye6D1xz+9WTRd0Ubw6TVfGwWbIAU+SSeiwafPdbWFsL1HqQjgV70hxd3zvUNdHJvNH5EiVeictzH9PuorGhGZwyHredJwHfjFYcvtSU7Nkms
  template:
    metadata:
      creationTimestamp: null
      name: matrix-secret
      namespace: matrix
    type: Opaque
